In [1]:
# Student grades predicted based on absence - Eaaa, Autumn 2021
# Sila, 23rd August 2021.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
col_names = ["Student_absence", "grade"]

In [4]:
df = pd.read_csv('StudentAbsenceGrade.csv')

In [5]:
df[['student_absence','grade']] = df['student_absence;grade'].str.split(';', expand=True)

In [6]:
print ( df .describe( include = 'all' ))

       student_absence;grade student_absence grade
count                    156             156   156
unique                    54              30     6
top                     31;7              23     7
freq                      14              24    58


In [7]:
# Remove empty cells

In [8]:
df.isnull().sum()

student_absence;grade    0
student_absence          0
grade                    0
dtype: int64

In [9]:
print(df)

    student_absence;grade student_absence grade
0                    0;10               0    10
1                    27;7              27     7
2                     0;7               0     7
3                    0;10               0    10
4                    65;0              65     0
..                    ...             ...   ...
151                  23;7              23     7
152                  62;2              62     2
153                  38;7              38     7
154                  54;0              54     0
155                  8;12               8    12

[156 rows x 3 columns]


In [10]:
#Replace values
df.loc[df['grade']=='0', 'grade'] = '2'
df.loc[df['grade']=='4', 'grade'] = '7'
df.loc[df['grade']=='10', 'grade'] = '12'

In [11]:
print(df)

    student_absence;grade student_absence grade
0                    0;10               0    12
1                    27;7              27     7
2                     0;7               0     7
3                    0;10               0    12
4                    65;0              65     2
..                    ...             ...   ...
151                  23;7              23     7
152                  62;2              62     2
153                  38;7              38     7
154                  54;0              54     2
155                  8;12               8    12

[156 rows x 3 columns]


In [12]:
X = df[ "student_absence" ]
y = df[ "grade" ]

In [13]:
#Option 1 - Reshaping to (-1,1)
X = np.array(X).reshape(-1,1)

In [14]:
print(y)

0      12
1       7
2       7
3      12
4       2
       ..
151     7
152     2
153     7
154     2
155    12
Name: grade, Length: 156, dtype: object


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=51 )
print ("Shape of X_train = ", X_train.shape)
print ("Shape of y_train = ", y_train.shape)
print ("Shape of X_test = ", X_test.shape)
print ("Shape of y_test = ", y_test.shape)

Shape of X_train =  (124, 1)
Shape of y_train =  (124,)
Shape of X_test =  (32, 1)
Shape of y_test =  (32,)


In [16]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(solver='lbfgs',
                    alpha=1e-5,
                    hidden_layer_sizes=(6,6),
                    random_state=1)

mlp.fit(X_train, y_train)

C:\Users\lynge\Desktop\kodeOpgaver\6_semester\modul7_pcaNeuralNets\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(6, 6), random_state=1,
              solver='lbfgs')

In [17]:
from sklearn.metrics import classification_report,confusion_matrix

In [18]:
#predictions
predictions = mlp.predict(X_test)

matrix = confusion_matrix(y_test,predictions)
print (matrix)
print (classification_report(y_test,predictions))

[[ 5  0  5]
 [ 0  5  1]
 [ 0  1 15]]
              precision    recall  f1-score   support

          12       1.00      0.50      0.67        10
           2       0.83      0.83      0.83         6
           7       0.71      0.94      0.81        16

    accuracy                           0.78        32
   macro avg       0.85      0.76      0.77        32
weighted avg       0.83      0.78      0.77        32
